### ISSUE TITLE
Getting type errors with Axios

### ISSUE THREAD

**Issue by charliematters** [total-typescript/shoehorn#6]
Hi,

`fromPartial` seems to work perfectly for replacing every type-cast in our test suite except when we do `fromPartial<AxioInstance>({})`. We're using Axios 0.27.2 and shoehorn 0.10, but it seems to be requiring all the fields of an instance. I can flesh out this ticket tomorrow with the actual error, but I thought I'd ask in case it's something obvious.

A Codesandbox showing the TS Error is here: https://codesandbox.io/s/falling-currying-pv8lfk?file=/src/Shoehorn.spec.ts:
>   Type '{}' is missing the following properties from type 'AxiosInstance': defaults, interceptors, getUri, request, and 10 more.ts(2345)

**Comment by mattpocock** [comment]
Interesting, I'll do some checking on this. It looks like AxiosInstance is a function? One with multiple overloads.

I could see that causing an issue.

**Comment by mattpocock** [comment]
Whoops, didn't mean to close.

**Comment by charliematters** [comment]
Thanks for looking into it. It's been integral to me removing hundreds of casts!

**Comment by mattpocock** [comment]
Fixed in 0.1.1
